spring:
  application:
    name: Grpc-Server
  datasource:
#加载类“com.mysql.jdbc.Driver”。 这是弃用。 新的驱动类是' com.mysql. jdbc. driver '。
#驱动程序是通过SPI自动注册的，手动加载驱动类通常是不必要的。
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.50.3.16:3306/cif?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
server:
  port: 8081


